---
- hosts: localhost
  connection: local
  tasks:
       - name: Create an Ec2 intance
         ec2:
           key_name: "{{ KEYNAME }}"
           instance_type: "{{ INSTANCE_TYPE }}"
           image: "{{ IMAGE }}"
           wait: yes
           count: "{{ COUNT }}"
           region: "{{ REGION }}"
           #aws_access_key: AKIAXP3NNGCCJKW4VDSF
           #           aws_secret_key: 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
           instance_tags:
                    Name: "{{ TAG }}"
           group: "{{ SG_GROUP }}"
